from .file_writer import ReportFileWriter
class ReportWriter():

    @staticmethod
    def write(report, writer=ReportFileWriter):
        #LOGICA...
        # LOGICA...
        # LOGICA...
        # LOGICA...
        # REPORT = FAZ ALGUMA OPERACAO
        writer.write(report)